

services:
  app:
    build: .
    container_name: email_server_frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:

      - ./prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=production


